resources:
  repositories:
    - repository: templates
      type: github
      name: ccdc-opensource/conan-azure-devops
      ref: refs/heads/development
      endpoint: github

extends:
  template: third-party-library-all-platforms-from-conan-center.yml@templates
  parameters:
    package: sqlite3
    package_version: 3.37.2
    source_repository: public-conan-center
    destination_repository: ccdc-3rdparty-conan
